// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRowCursor wrapper class

class CRowCursor : public COleDispatchDriver
{
public:
	CRowCursor() {}		// Calls COleDispatchDriver default constructor
	CRowCursor(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRowCursor(const CRowCursor& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};
